CREATE TABLE visitors (id SERIAL PRIMARY KEY, time TIMESTAMP);
CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT UNIQUE, password TEXT);
CREATE TABLE courses ( id SERIAL PRIMARY KEY, title TEXT UNIQUE, description TEXT, user_id INTEGER REFERENCES users ON DELETE CASCADE, sent_at TIMESTAMP);
CREATE TABLE coursecontent (id SERIAL PRIMARY KEY, course_id INTEGER REFERENCES courses ON DELETE CASCADE, textcontent TEXT);
CREATE TABLE coursetext (id SERIAL PRIMARY KEY, course_id INTEGER REFERENCES coursecontent ON DELETE CASCADE, textmaterial TEXT, page INTEGER, pagelocation INTEGER);